export  const Data={// À ajouter dans DICT.fr et DICT.en
fr: {
  wa_title: "QR Code WhatsApp Direct",
  wa_sub: "Générez un lien direct pour ouvrir instantanément une discussion WhatsApp avec vos clients.",
  label_phone: "Numéro de téléphone (avec indicatif)",
  ph_phone: "Ex: 33612345678",
  label_wa_msg: "Message pré-rempli (optionnel)",
  ph_wa_msg: "Ex: Bonjour, je souhaite commander un article...",
  wa_tip: "💡 Conseil : Le message s'écrira automatiquement dans le téléphone du client lorsqu'il scannera le code.",
  btn_dl_wa: "TÉLÉCHARGER LE QR WHATSAPP",
   btn_dl_plaque: "✨ TÉLÉCHARGER LA PLAQUE PRO",
  plaque_title: "CONTACTEZ-NOUS SUR WHATSAPP",
  plaque_footer: "Scannez pour démarrer la discussion",
  
  mode_direct: "Vente & Support",
  mode_channel: "Diffusion & News",
  desc_direct: "Idéal pour recevoir des commandes. Le client vous envoie un message pré-rempli directement sur votre numéro.",
  desc_channel: "Idéal pour fidéliser. Le client rejoint votre chaîne pour recevoir vos actus, promos et nouveautés.",
  label_channel_url: "Lien de votre Chaîne WhatsApp",
  ph_channel_url: "https://whatsapp.com/channel/...",
  plaque_title_channel: "REJOIGNEZ NOTRE CHAÎNE",
  plaque_footer_channel: "Scannez pour ne rater aucune promo",
  no_number: "Numéro ou lien requis",
  label_biz_name: "Nom de votre établissement (Optionnel)",
  ph_biz_name: "Ex: Café de la Gare",
  label_logo: "Votre Logo (Optionnel)",
  ph_logo: "Uploader un logo (PNG/JPG)",
},
en: {
  wa_title: "Direct WhatsApp QR",
  wa_sub: "Generate a direct link to instantly open a WhatsApp chat with your customers.",
  label_phone: "Phone Number (with country code)",
  ph_phone: "e.g. 44123456789",
  label_wa_msg: "Pre-filled message (optional)",
  ph_wa_msg: "e.g. Hello, I would like to order an item...",
  wa_tip: "💡 Tip: The message will be automatically typed in the customer's phone when they scan the code.",
  btn_dl_wa: "DOWNLOAD WHATSAPP QR",
  btn_dl_plaque: "✨ DOWNLOAD PRO POSTER",
  plaque_title: "CONTACT US ON WHATSAPP",
  plaque_footer: "Scan to start chatting",

  mode_direct: "Sales & Support",
  mode_channel: "Broadcast & News",
  desc_direct: "Perfect for orders. Customers send you a pre-filled message directly to your number.",
  desc_channel: "Perfect for loyalty. Customers join your channel to get your latest news and promos.",
  label_channel_url: "WhatsApp Channel Link",
  ph_channel_url: "https://whatsapp.com/channel/...",
  plaque_title_channel: "JOIN OUR CHANNEL",
  plaque_footer_channel: "Scan to get our latest updates",
  no_number: "Number or link required",
    label_biz_name: "Business Name (Optional)",
  ph_biz_name: "e.g. Station Cafe",
  label_logo: "Your Logo (Optional)",
  ph_logo: "Upload a logo (PNG/JPG)",

}}