export const Data = {
  fr: {
    event_info: "Détails de l'événement",
    register_title: "Réservez votre place",
    register_sub: "L'inscription est gratuite. Vous recevrez un ticket QR unique.",
    label_name: "Nom complet",
    ph_name: "Jean Dupont",
    btn_register: "S'inscrire maintenant",
    success_msg: "Félicitations ! Vous êtes inscrit.",
    download_ticket: "Télécharger mon ticket QR",
    capacity_full: "Désolé, cet événement est complet.",
    back_home: "Retour à l'accueil",
    hosted_by: "Organisé par",
    security_note: "Vos données sont protégées et ne seront utilisées que pour cet événement.",
    list_title: "Événements & Meetups Retail",
    list_sub: "Découvrez les prochains rendez-vous de la communauté RetailBox.",
    no_events: "Aucun événement public n'est prévu pour le moment.",
    search_ph: "Rechercher un événement...",
    btn_view: "Voir les détails",
    event_count: "événements à venir",
    card_start: "Début de l'événement",
    
  },
  en: {
    event_info: "Event Details",
    register_title: "Reserve your spot",
    register_sub: "Registration is free. You will receive a unique QR ticket.",
    label_name: "Full Name",
    ph_name: "John Doe",
    btn_register: "Register Now",
    success_msg: "Congratulations! You are registered.",
    download_ticket: "Download my QR Ticket",
    capacity_full: "Sorry, this event is full.",
    back_home: "Back to home",
    hosted_by: "Hosted by",
    security_note: "Your data is protected and will only be used for this event.",
    list_title: "Retail Events & Meetups",
    list_sub: "Discover the upcoming events from the RetailBox community.",
    no_events: "No public events scheduled at the moment.",
    search_ph: "Search events...",
    btn_view: "View Details",
    event_count: "upcoming events",
    card_start: "Event Start",
  }
};