  export const Data={// À ajouter dans DICT.fr et DICT.en
fr: {
  short_title: "RetailLink : Réducteur & Statistiques",
  short_sub: "Créez des URLs courtes et suivez l'engagement de vos clients en temps réel.",
  label_long_url: "Lien de destination (URL longue)",
  ph_long_url: "https://votre-boutique.com/produit-tres-long",
  label_custom_alias: "Alias personnalisé (Optionnel)",
  ph_custom_alias: "Ex: promo-printemps",
  short_info: "Laissez vide pour un code aléatoire. Pas d'espaces, uniquement lettres et chiffres.",
  btn_shorten: "🚀 Réduire et Activer",
  short_success: "✅ Votre RetailLink est prêt !",
  qr_track_info: "Ce QR Code redirige vers votre lien court et permet de compter les scans.",
  btn_copy: "Copier le lien",
  btn_dl_qr: "Télécharger le QR",
  btn_stats: "📊 Voir les statistiques",
  err_alias_taken: "❌ Cet alias est déjà utilisé. Choisissez-en un autre.",
},
en: {
  short_title: "RetailLink: Shortener & Analytics",
  short_sub: "Create short URLs and track your customer engagement in real-time.",
  label_long_url: "Destination link (Long URL)",
  ph_long_url: "https://your-shop.com/very-long-product-link",
  label_custom_alias: "Custom alias (Optional)",
  ph_custom_alias: "e.g. spring-sale",
  short_info: "Leave blank for a random code. No spaces, letters and numbers only.",
  btn_shorten: "🚀 Shorten & Activate",
  short_success: "✅ Your RetailLink is ready!",
  qr_track_info: "This QR Code redirects to your short link and tracks every scan.",
  btn_copy: "Copy link",
  btn_dl_qr: "Download QR",
  btn_stats: "📊 View Analytics",
  err_alias_taken: "❌ This alias is already taken. Please try another.",
}}