// components/builders/_shared/data.ts
export const sharedBuilderData = {
  fr: {
    title: "Créateur de Design",
    templates: "Templates",
    preview:"Aperçu",
    toolbar: {
      text: "Texte",
      shapes: "Formes",
      image: "Image",
      export: "Exporter",
      templatesBtn: "Templates",
    },
    properties: "Propriétés",
    noSelection: "Aucun élément sélectionné",
    fillColor: "Couleur de remplissage",
    stroke: "Contour",
    fontSize: "Taille de la police",
    alignment: "Alignement",
    left:"Gauche",
    right:"Droite",
    center:"Centre",
    rotation: "Rotation",
    opacity: "Opacité",
    shadow: "Ombre",
    duplicate: "Dupliquer",
    delete: "Supprimer",
    bring_to_front:"↑ Amener devant",
    sent_to_back:" ↓ Renvoyer deriére",

    
    shapesPanel: {
      title: "Insérer une forme",
      rectangle: "Rectangle",
      circle: "Cercle",
      line: "Ligne",
      arrow: "Flèche",
    },
  },
  en: {
    title: "Design Builder",
    templates: "Templates",
    preview:"Preview",
    toolbar: {
      text: "Text",
      shapes: "Shapes",
      image: "Image",
      export: "Export",
      templatesBtn: "Templates",
    },
    properties: "Properties",
    noSelection: "No element selected",
    fillColor: "Fill color",
    stroke: "Stroke",
    fontSize: "Font size",
    alignment: "Alignment",
    left:"Left",
    right:"Right",
    center:"Center",
    rotation: "Rotation",
    opacity: "Opacity",
    shadow: "Shadow",
    duplicate: "Duplicate",
    
    delete: "Delete",
    bring_to_front:"↑ Bring to Front",
    sent_to_back:" ↓ Send to Back",
    shapesPanel: {
      title: "Insert shape",
      rectangle: "Rectangle",
      circle: "Circle",
      line: "Line",
      arrow: "Arrow",
    },
  },
} as const;