export const Data = {
  fr: {
    title: "Mes Événements",
    sub: "Gérez vos séminaires, conférences et ateliers.",
    btn_new: "Créer un événement",
    no_events: "Aucun événement organisé pour le moment.",
    card_participants: "Inscrits",
    card_start: "Début",
    card_end: "Fin",
    btn_manage: "Gérer",
    btn_link: "Lien public",
    status_draft: "Brouillon",
    status_live: "En ligne",
    new_title: "Créer un événement",
  new_sub: "Remplissez les détails pour lancer vos inscriptions.",
  label_title: "Nom de l'événement",
  label_desc: "Description / Programme",
  label_start: "Date et Heure de début",
  label_end: "Date et Heure de fin (Optionnel)",
  label_location: "Lieu / Adresse",
  label_capacity: "Capacité maximale (Optionnel)",
  btn_create: "🚀 Publier l'événement",
  success_create: "Événement créé avec succès !",
   edit_title: "Modifier l'événement",
  btn_update: "Mettre à jour",
  public_register_title: "Réserver ma place",
  public_register_sub: "L'inscription est gratuite et instantanée.",
  label_full_name: "Nom complet",
  ph_full_name: "Ex: Jean Dupont",
  btn_register: "S'inscrire maintenant",
  register_success: "Félicitations ! Vous êtes inscrit. Votre ticket QR a été généré.",
  event_full: "Désolé, cet événement est complet.",
  back_to_events: "Retour à la liste",
   admin_title: "Tableau de bord Événement",
  stat_total: "Total Inscrits",
  stat_checked: "Présences validées",
  stat_capacity: "Taux de remplissage",
  list_name: "Participant",
  list_status: "Statut",
  list_date: "Date d'inscription",
  status_registered: "Inscrit",
  status_checked: "Présent",
  btn_scan: "Scanner les tickets",
  no_participants: "Aucun inscrit pour le moment.",
  list_participants:"Liste des participants"

  },
  en: {
    title: "My Events",
    sub: "Manage your seminars, conferences, and workshops.",
    btn_new: "Create Event",
    no_events: "No events organized yet.",
    card_participants: "Registrations",
    card_start: "Start",
    card_end: "End",
    btn_manage: "Manage",
    btn_link: "Public Link",
    status_draft: "Draft",
    status_live: "Live",
     new_title: "Create New Event",
  new_sub: "Fill in the details to start registrations.",
  label_title: "Event Name",
  label_desc: "Description / Schedule",
  label_start: "Start Date & Time",
  label_end: "End Date & Time (Optional)",
  label_location: "Location / Address",
  label_capacity: "Max Capacity (Optional)",
  btn_create: "🚀 Publish Event",
  success_create: "Event created successfully!",
    edit_title: "Edit Event",
  btn_update: "Update Event",
  public_register_title: "Reserve my spot",
  public_register_sub: "Registration is free and instant.",
  label_full_name: "Full Name",
  ph_full_name: "e.g. John Doe",
  btn_register: "Register Now",
  register_success: "Congratulations! You are registered. Your QR ticket has been generated.",
  event_full: "Sorry, this event is full.",
  back_to_events: "Back to list",
    admin_title: "Event Dashboard",
  stat_total: "Total Registered",
  stat_checked: "Checked-in",
  stat_capacity: "Capacity Rate",
  list_name: "Participant",
  list_status: "Status",
  list_date: "Registration Date",
  status_registered: "Registered",
  status_checked: "Present",
  btn_scan: "Scan Tickets",
  no_participants: "No registrations yet.",
  list_participants:"Participant List"
  }
};