export const Data = {
  fr: {
    title: "Mes Événements",
    sub: "Gérez vos séminaires, conférences et ateliers.",
    btn_new: "Créer un événement",
    no_events: "Aucun événement organisé pour le moment.",
    card_participants: "Inscrits",
    card_start: "Début",
    card_end: "Fin",
    btn_manage: "Gérer",
    btn_link: "Lien public",
    status_draft: "Brouillon",
    status_live: "En ligne",
    new_title: "Créer un événement",
  new_sub: "Remplissez les détails pour lancer vos inscriptions.",
  label_title: "Nom de l'événement",
  label_desc: "Description / Programme",
  label_start: "Date et Heure de début",
  label_end: "Date et Heure de fin (Optionnel)",
  label_location: "Lieu / Adresse",
  label_capacity: "Capacité maximale (Optionnel)",
  btn_create: "🚀 Créer l'événement",
  success_create: "Événement créé avec succès !",
   edit_title: "Modifier l'événement",
  btn_update: "Mettre à jour",
  public_register_title: "Réserver ma place",
  public_register_sub: "L'inscription est gratuite et instantanée.",
  label_full_name: "Nom complet",
  ph_full_name: "Ex: Jean Dupont",
  btn_register: "S'inscrire maintenant",
  register_success: "Félicitations ! Vous êtes inscrit. Votre ticket QR a été généré.",
  event_full: "Désolé, cet événement est complet.",
  back_to_events: "Retour à la liste",
   admin_title: "Tableau de bord Événement",
  stat_total: "Total Inscrits",
  stat_checked: "Présences validées",
  stat_capacity: "Taux de remplissage",
  list_name: "Participant",
  list_status: "Statut",
  list_date: "Date d'inscription",
  status_registered: "Inscrit",
  status_checked: "Présent",
  btn_scan: "Scanner les tickets",
  no_participants: "Aucun inscrit pour le moment.",
  list_participants:"Liste des participants",
   label_category: "Catégorie d'événement",
  label_visibility: "Visibilité",
  label_registration: "Système d'inscription",
  opt_public: "Public (Visible sur le site)",
  opt_private: "Privé (Lien direct uniquement)",
  opt_reg_yes: "Inscription obligatoire (Tickets QR)",
  opt_reg_no: "Entrée libre (Pas de tickets)",
  cat_sales: "Ventes & Showroom",
  cat_training: "Formation & Atelier",
  cat_networking: "Networking & Conférence",
  cat_other: "Autre",
  tab_overview: "Vue d'ensemble",
  tab_agenda: "Programme / Agenda",
  tab_invites: "Invitations VIP",
  label_session: "Titre de la session",
  label_room: "Salle / Showroom",
  label_speakers: "Intervenants (séparés par des virgules)",
  btn_add_session: "+ Ajouter au programme",
  invite_email: "Adresse e-mail de l'invité",
  btn_send_invite: "Envoyer l'invitation",
  invite_status_pending: "En attente",
  btn_resend: "Relancer",
  remind_info: "Seuls les invités n'ayant pas encore accepté recevront la relance.",
   tab_comms: "Communications",
  comm_title: "Branding & Emails",
  label_org_name: "Nom de l'organisateur (Raison sociale)",
  label_org_logo: "Logo de l'organisateur (Optionnel)",
  label_sponsors: "Logos des Sponsors (Max 4)",
  label_useful_info: "Informations utiles (Accès, Wi-Fi, Parking...)",
  auto_confirm_title: "Emails de confirmation",
  auto_confirm_desc: "Envoyer automatiquement un mail après chaque inscription.",
  bulk_badge_title: "Envoi massif des badges",
  bulk_badge_desc: "Envoyer le ticket QR par e-mail à tous les inscrits.",
  btn_send_all: "🚀 Envoyer à {n} personnes",
  msg_soon: "Module d'envoi d'emails en cours d'activation (Beta)",
  no_programm:"Aucun programme défini.",
    btn_publish: "🚀 Publier l'événement",
  btn_unpublish: "🛑 Passer en brouillon",
  automation_title: "Stratégie d'envoi des badges",
  opt_manual: "Envoi manuel (via bouton)",
  opt_immediate: "Envoi immédiat (dès l'inscription)",
  opt_scheduled: "Programmé (X heures avant début)",
  label_delay: "Délai avant l'événement (heures)",
  save_automation: "Mettre à jour la stratégie"

  },
  en: {
    title: "My Events",
    sub: "Manage your seminars, conferences, and workshops.",
    btn_new: "Create Event",
    no_events: "No events organized yet.",
    card_participants: "Registrations",
    card_start: "Start",
    card_end: "End",
    btn_manage: "Manage",
    btn_link: "Public Link",
    status_draft: "Draft",
    status_live: "Live",
     new_title: "Create New Event",
  new_sub: "Fill in the details to start registrations.",
  label_title: "Event Name",
  label_desc: "Description / Schedule",
  label_start: "Start Date & Time",
  label_end: "End Date & Time (Optional)",
  label_location: "Location / Address",
  label_capacity: "Max Capacity (Optional)",
  btn_create: "🚀 Create Event",
  success_create: "Event created successfully!",
  edit_title: "Edit Event",
  btn_update: "Update Event",
  public_register_title: "Reserve my spot",
  public_register_sub: "Registration is free and instant.",
  label_full_name: "Full Name",
  ph_full_name: "e.g. John Doe",
  btn_register: "Register Now",
  register_success: "Congratulations! You are registered. Your QR ticket has been generated.",
  event_full: "Sorry, this event is full.",
  back_to_events: "Back to list",
  admin_title: "Event Dashboard",
  stat_total: "Total Registered",
  stat_checked: "Checked-in",
  stat_capacity: "Capacity Rate",
  list_name: "Participant",
  list_status: "Status",
  list_date: "Registration Date",
  status_registered: "Registered",
  status_checked: "Present",
  btn_scan: "Scan Tickets",
  no_participants: "No registrations yet.",
  list_participants:"Participant List",
  label_category: "Event Category",
  label_visibility: "Visibility",
  label_registration: "Registration System",
  opt_public: "Public (Visible on site)",
  opt_private: "Private (Direct link only)",
  opt_reg_yes: "Registration required (QR Tickets)",
  opt_reg_no: "Open Entry (No tickets)",
  cat_sales: "Sales & Retail",
  cat_training: "Training & Workshop",
  cat_networking: "Networking & Conference",
  cat_other: "Other",
   tab_overview: "Overview",
  tab_agenda: "Agenda / Schedule",
  tab_invites: "VIP Invitations",
  label_session: "Session Title",
  label_room: "Room / Showroom",
  label_speakers: "Speakers (comma separated)",
  btn_add_session: "+ Add to Agenda",
  invite_email: "Guest email address",
  btn_send_invite: "Send Invitation",
  invite_status_pending: "Pending",
  btn_resend: "Resend",
  remind_info: "Only guests who haven't accepted yet will receive the reminder.",
   tab_comms: "Communications",
  comm_title: "Branding & Emails",
  label_org_name: "Organizer Name (Company Name)",
  label_org_logo: "Organizer Logo (Optional)",
  label_sponsors: "Sponsor Logos (Max 4)",
  label_useful_info: "Useful Information (Access, Wi-Fi, Parking...)",
  auto_confirm_title: "Confirmation Emails",
  auto_confirm_desc: "Automatically send an email after each registration.",
  bulk_badge_title: "Bulk Badge Sending",
  bulk_badge_desc: "Send the QR ticket by email to all registered participants.",
  btn_send_all: "🚀 Send to {n} people",
  msg_soon: "Email sending module being activated (Beta)",
  no_programm:"No programm defined yet",
   btn_publish: "🚀 Publish Event",
  btn_unpublish: "🛑 Set to Draft",
  automation_title: "Badge Sending Strategy",
  opt_manual: "Manual sending (via button)",
  opt_immediate: "Immediate sending (after sign-up)",
  opt_scheduled: "Scheduled (X hours before start)",
  label_delay: "Time before event (hours)",
  save_automation: "Update Strategy"
  }
};