export const Data= {fr: {
  soldes_title: "Étiquettes de Soldes & Planches A4",
  soldes_sub: "Générez des étiquettes professionnelles avec prix barrés et codes-barres.",
  label_item: "Nom du produit",
  label_prices: "Configuration des prix",
  old_price: "Prix d'origine (€)",
  new_price: "Prix soldé (€)",
  label_barcode: "Code-barres EAN-13 (12 chiffres)",
  btn_generate: "🚀 Créer l'étiquette et la planche",
  preview_title: "Aperçu de l'étiquette",
  dl_image: "⬇️ Image seule (PNG)",
  dl_pdf: "📄 Planche A4 (24 étiquettes)",
},
en: {
  soldes_title: "Sale Labels & A4 Sheets",
  soldes_sub: "Generate professional labels with crossed-out prices and barcodes.",
  label_item: "Product Name",
  label_prices: "Price Configuration",
  old_price: "Original Price (€)",
  new_price: "Sale Price (€)",
  label_barcode: "EAN-13 Barcode (12 digits)",
  btn_generate: "🚀 Create Label & Sheet",
  preview_title: "Label Preview",
  dl_image: "⬇️ Single Image (PNG)",
  dl_pdf: "📄 A4 Sheet (24 labels)",
}}