export const Data = {
  fr: {
    title: "Mes Formulaires & Sondages",
    sub: "Gérez vos enquêtes de satisfaction et collectez des avis clients.",
    btn_new: "Créer un formulaire",
    btn_publish:"Publier",
    btn_unpublish: "🛑 Passer en brouillon",
    no_forms: "Vous n'avez pas encore créé de formulaire.",
     back_to_forms: "Retour à la liste",
    card_responses: "Réponses reçues",
    card_created: "Créé le",
    btn_manage: "Voir les résultats",
    btn_link: "Lien de réponse",
    status_active: "Actif",
    status_closed: "Fermé",
    category_survey: "Sondage",
    category_satisfaction: "Satisfaction",
     admin_title: "Analyse du formulaire",
  stat_total_resp: "Réponses totales",
  stat_avg_score: "Score de satisfaction",
  stat_last_activity: "Dernière réponse",
  share_title: "Diffusion du sondage",
  share_desc: "Utilisez ce lien ou le QR Code pour collecter des avis sur vos tickets ou en caisse.",
  table_date: "Date",
  table_answers: "Réponses",
  no_responses: "Aucune réponse pour le moment.",
  btn_export: "Exporter CSV",
  btn_delete_resp: "Vider les données",


  edit_form_title: "Modifier le formulaire",
  edit_warning: "Attention : Si vous modifiez ou supprimez des questions alors que vous avez déjà reçu des réponses, cela peut impacter la cohérence de vos statistiques.",
  btn_update_form: "Mettre à jour le formulaire",
  save_success: "Formulaire mis à jour !"
  },
  en: {
    title: "My Forms & Surveys",
    sub: "Manage your satisfaction surveys and collect customer feedback.",
    btn_new: "Create Form",
    btn_publish:"Publish",
    btn_unpublish: "🛑 Set to Draft",
    no_forms: "You haven't created any forms yet.",
     back_to_forms: "Back to forms",
    card_responses: "Responses",
    card_created: "Created on",
    btn_manage: "View Results",
    btn_link: "Response Link",
    status_active: "Active",
    status_closed: "Closed",
    category_survey: "Survey",
    category_satisfaction: "Satisfaction",

  admin_title: "Form Analytics",
  stat_total_resp: "Total Responses",
  stat_avg_score: "Satisfaction Score",
  stat_last_activity: "Last Activity",
  share_title: "Survey Distribution",
  share_desc: "Use this link or QR Code to collect feedback on receipts or at checkout.",
  table_date: "Date",
  table_answers: "Answers",
  no_responses: "No responses yet.",
  btn_export: "Export CSV",
  btn_delete_resp: "Clear data",

   edit_form_title: "Edit Form",
  edit_warning: "Warning: If you modify or delete questions after receiving responses, it may affect the consistency of your analytics.",
  btn_update_form: "Update Form",
  save_success: "Form updated successfully!"
  }
};