export const Data={
    // À ajouter dans DICT.fr et DICT.en
fr: {
    title: "Paramètres de votre Espace",
    sub: "Gérez votre identité professionnelle et la sécurité de votre compte.",
   tab_profile: "Profil Public",
    tab_account: "Compte & Sécurité",
    profile_sec: "Identité Professionnelle",
    profile_sub: "Ces informations seront utilisées pour vos VCards et votre Identité Digitale.",
    label_fname: "Prénom",
    label_lname: "Nom",
    label_job: "Poste / Titre",
    label_company: "Boutique / Entreprise",
    label_phone: "Téléphone pro",
    label_web: "Site internet",
    label_linkedin: "URL LinkedIn",
    btn_save_profile: "Sauvegarder le profil",
    update_success: "Mises à jour enregistrées !",
  settings_title: "Paramètres du compte",
  settings_sub: "Gérez vos informations personnelles et vos préférences de sécurité.",

  connexion_sec: "Connexion & Sécurité",
  label_display_name: "Nom complet",
  label_email: "Adresse e-mail",
  label_new_pass: "Nouveau mot de passe",
  btn_update: "Mettre à jour le profil",
  btn_pass: "Changer le mot de passe",
  danger_zone: "Zone de danger",
  delete_account: "Supprimer mon compte",
  delete_warn: "Cette action est irréversible. Toutes vos données (liens, commerces) seront supprimées.",
  tab_social: "Réseaux Sociaux",
    social_sec: "Présence Digitale",
    social_sub: "Configurez les liens qui apparaîtront sur votre Identity Card.",
    btn_add_social: "+ Ajouter un réseau",
    label_platform: "Plateforme",
    label_link: "Lien ou Identifiant",
  
},
en: {
  title: "Space Settings",
  sub: "Manage your professional identity and account security.",
 tab_profile: "Public Profile",

    tab_account: "Account & Security",
    profile_sec: "Professional Identity",
    profile_sub: "This information will be used for your VCards and Digital Identity.",
    label_fname: "First Name",
    label_lname: "Last Name",
    label_job: "Job Title",
    label_company: "Shop / Company",
    label_phone: "Pro Phone",
    label_web: "Website",
    label_linkedin: "LinkedIn URL",
    btn_save_profile: "Save Profile",
    update_success: "Updates saved!",
  settings_title: "Account Settings",
  settings_sub: "Manage your personal information and security preferences.",

  connexion_sec: "Connection & Security",
  label_display_name: "Full Name",
  label_email: "Email Address",
  label_new_pass: "New Password",
  btn_update: "Update Profile",
  btn_pass: "Change Password",
  danger_zone: "Danger Zone",
  delete_account: "Delete my account",
  delete_warn: "This action is irreversible. All your data (links, businesses) will be deleted.",
  tab_social: "Social Media",
  social_sec: "Digital Presence",
  social_sub: "Configure the links that will appear on your Identity Card.",
  btn_add_social: "+ Add a network",
  label_platform: "Platform",
  label_link: "Link or Handle",
  
}
}