export const Data = {
  fr: {
    dashboard: "Tableau de bord",
    my_links: "Mes Liens",
    analytics: "Statistiques",
    google_reviews: "Avis Google",
    settings: "Paramètres",
    logout: "Déconnexion",
    brand: "RetailLink",
    back_to_tools: "Outils Création",
    workspace: "Espace",
    beta: "Bientôt",
    business_title:"Mon Business",
    qwick_acces:"Accés Rapide",
    search:"Lancer la recherche",
    my_businesses: "Mes Établissements",
  no_businesses: "Aucun établissement lié pour le moment.",
  add_business: "Lier un commerce",
  business_total: "établissements enregistrés",
  manage: "Gérer",
  last_scan: "Dernier scan",
today: "Aujourd'hui",
no_loyalty_activity: "Aucune activité de fidélité pour le moment.",
    
  },
  en: {
    dashboard: "Dashboard",
    my_links: "My Links",
    analytics: "Analytics",
    google_reviews: "Google Reviews",
    settings: "Settings",
    logout: "Logout",
    brand: "RetailLink",
    back_to_tools: "Creation Tools",
    workspace: "Pro Space",
    beta: "Beta",
    business_title:"My Business",
    qwick_access:"Qwick Acces",
    search:'Search',
     my_businesses: "My Businesses",
  no_businesses: "No business linked yet.",
  add_business: "Link a business",
  business_total: "registered businesses",
  manage: "Manage",
  last_scan: "Last scan",
today: "Today",
no_loyalty_activity: "No loyalty activity yet.",
  }
};