export const Data = {
  fr: {
    builder_title: "Conception du formulaire",
    builder_desc: "Ajoutez, organisez et configurez vos questions.",
    add_field: "Ajouter un champ",
    tab_design: "Design",
    tab_preview: "Aperçu",
    btn_save: "Sauvegarder le modèle",
    btn_submit:"Envoyer",
    btn_next:"Suivant",
    btn_add_option: "+ Ajouter une option",
    label_required: "Obligatoire",
    label_range_config: "Configuration du curseur",
    placeholder_q: "Votre question ici...",
    placeholder_help: "Texte d'aide (Ex: Entrez votre avis)",
    min_label: "Label Gauche (ex: Mauvais)",
    max_label: "Label Droite (ex: Excellent)",
    definely_not:"Pas du tout",
    absolutely:"Absolument",
    classic_mode:"Classic",
    animated_mode:"Animé",
    add_first_fields:"Ajoutez vos premiers champs ci-dessus",
    types: {
  text: 'Texte',
  number: 'Nombre',
  email: 'Email',
  phone: 'Téléphone',
  date: 'Date',
  select: 'Liste',
  multiselect: 'Choix multiple',
  range: 'Curseur',
  stars: 'Étoiles',
  nps: 'Score NPS',
  image_choice: 'Choix image',
},
label_stars_config: 'Nombre d\'étoiles',
label_phone_config: 'Pays par défaut',
    
  },
  en: {
    builder_title: "Form Design",
    builder_desc: "Add, organize, and configure your questions.",
    add_field: "Add field",
    tab_design: "Design",
    tab_preview: "Preview",
    btn_save: "Save Template",
    btn_submit:"Submit",
    btn_next:"Next",
    btn_add_option: "+ Add option",
    label_required: "Required",
    label_range_config: "Slider Settings",
    placeholder_q: "Your question here...",
    placeholder_help: "Help text (e.g. Enter your feedback)",
    min_label: "Left Label (e.g. Bad)",
    max_label: "Right Label (e.g. Excellent)",
    definely_not:"Not at all",
    absolutely:"Absolutely",
    classic_mode:"Classic",
    animated_mode:"Animated",
    add_first_fields:"Add your first fields above",
    // en
types: {
  text: 'Text',
  number: 'Number',
  email: 'Email',
  phone: 'Phone',
  date: 'Date',
  select: 'Select',
  multiselect: 'Multi-select',
  range: 'Slider',
  stars: 'Stars',
  nps: 'NPS Score',
  image_choice: 'Image choice',
},
label_stars_config: 'Number of stars',
label_phone_config: 'Default country',
  }
};